files:
  - source: '/src/main/resources/hudson/plugins/msbuild/**/*.properties'
    ignore:
      - '/src/main/resources/hudson/plugins/msbuild/**/%file_name%_%two_letters_code%.properties'
    translation: '/src/main/resources/hudson/plugins/msbuild/**/%file_name%_%two_letters_code%.properties'
    escape_quotes: 1
    escape_special_characters: 0
  - source: '/src/main/resources/hudson/plugins/msbuild/**/*.html'
    ignore:
    - '/src/main/resources/hudson/plugins/msbuild/**/%file_name%_%two_letters_code%.html'
    translation: '/src/main/resources/hudson/plugins/msbuild/**/%file_name%_%two_letters_code%.html'
    escape_quotes: 0
    escape_special_characters: 0

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN